services:
  server:
    build: ./server
    container_name: devsync-server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env

  client:
    build: ./client
    container_name: devsync-client
    ports:
      - "80:80"
    depends_on:
      - server