apiVersion: v1
kind: Secret
metadata:
  name: devsync-secrets
  labels:
    app: devsync
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL2RldnN5bmMtbW9uZ28tc2VydmljZToyNzAxNy9kZXZzeW5j
  JWT_SECRET: ZGV2c3luY19zdXBlcl9zZWNyZXRfa2V5XzIwMjY=
  JWT_REFRESH_SECRET: ZGV2c3luY19yZWZyZXNoX3NlY3JldF9rZXlfMjAyNg==
  EMAIL_USER: c2Fsb2tAZ21haWwuY29t
  EMAIL_PASS: YWtraWJlaGFuYWFzYWxvbmk=
  JWT_EXPIRE: N2Q=
